CREATE SCHEMA IF NOT EXISTS dbtest;
CREATE TABLE IF NOT EXISTS ACCOUNT(
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL,
    isAdmin SMALLINT DEFAULT FALSE
);