spring:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/RestfulTest
    username: root
    password: 123456
    minIdle: 5
    maxIdle: 10
    maxOpenPreparedStatements: 100
